In [27]:
import numpy

In [28]:
numpy.linspace?

In [29]:
Q1=numpy.linspace(4, 23,43)

In [30]:
Q1[5]

6.2619047619047619

In [31]:
ones_array = numpy.ones((5,17))

In [32]:
print(ones_array)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [33]:
zeros_array = numpy.zeros( ones_array.shape)
print(zeros_array)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [34]:
p=7
r=numpy.array([11.2, 4.7, 6.6])

In [35]:
numpy.sin?

In [36]:
Q3=(numpy.sin(p/r))**3

In [37]:
print(Q3)

[ 0.20030151  0.99009101  0.66454238]
