In [17]:
import numpy as np
from math import sin, cos, log, ceil

In [18]:
ar = np.linspace(0,10,11)
print(ar)

[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]


In [19]:
print(ar[3:8:2])

[ 3.  5.  7.]


In [20]:
print(ceil(0.524))

1


In [21]:
?ceil

In [26]:
dt_val = np.array([0.1, 0.05, 0.03, 0.002])
u_val = np.empty_like(dt_val, dtype=np.ndarray)

In [28]:
for i, dt in enumerate(dt_val):
    u = np.empty((6,4))
    u[0] = np.array([2, 3, 5, 7])
    #print(dt)
    for n in range(5):
        
        u[n+1] = u[n] + dt*3
        
    u_val[i] = u

In [32]:
print(u_val)

[ array([[ 2. ,  3. ,  5. ,  7. ],
       [ 2.3,  3.3,  5.3,  7.3],
       [ 2.6,  3.6,  5.6,  7.6],
       [ 2.9,  3.9,  5.9,  7.9],
       [ 3.2,  4.2,  6.2,  8.2],
       [ 3.5,  4.5,  6.5,  8.5]])
 array([[ 2.  ,  3.  ,  5.  ,  7.  ],
       [ 2.15,  3.15,  5.15,  7.15],
       [ 2.3 ,  3.3 ,  5.3 ,  7.3 ],
       [ 2.45,  3.45,  5.45,  7.45],
       [ 2.6 ,  3.6 ,  5.6 ,  7.6 ],
       [ 2.75,  3.75,  5.75,  7.75]])
 array([[ 2.  ,  3.  ,  5.  ,  7.  ],
       [ 2.09,  3.09,  5.09,  7.09],
       [ 2.18,  3.18,  5.18,  7.18],
       [ 2.27,  3.27,  5.27,  7.27],
       [ 2.36,  3.36,  5.36,  7.36],
       [ 2.45,  3.45,  5.45,  7.45]])
 array([[ 2.   ,  3.   ,  5.   ,  7.   ],
       [ 2.006,  3.006,  5.006,  7.006],
       [ 2.012,  3.012,  5.012,  7.012],
       [ 2.018,  3.018,  5.018,  7.018],
       [ 2.024,  3.024,  5.024,  7.024],
       [ 2.03 ,  3.03 ,  5.03 ,  7.03 ]])]
